name: library_app
description: "Omkar Reading Library app"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

#------------------------  PACKAGES  ------------------------#

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  #http: ^1.2.2
  get: ^4.6.6
  fluttertoast: ^8.2.8
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  flutter_spinkit: ^5.2.1
  pdf: ^3.11.1
  printing: ^5.13.2
  #image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.0.2
  #image_cropper: ^8.0.2
  image_picker: ^0.8.5+3
  image_editor:
  image_cropper:
  dotted_border :

#------------------------  PACKAGES END ------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  #------------------------  LOCAL ASSETS ------------------------#

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/fonts/



  #------------------------  LOCAL FONTS ------------------------#
  
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-Black.ttf
        - asset: assets/fonts/Lexend/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend/Lexend-ExtraBold.ttf
        - asset: assets/fonts/Lexend/Lexend-ExtraLight.ttf
        - asset: assets/fonts/Lexend/Lexend-Light.ttf
        - asset: assets/fonts/Lexend/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend/Lexend-Thin.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-Regular.ttf
          weight: 300


  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
